# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     10

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     /:year/:month/:day/:title.html
paginate_path: /page/:num
timezone:      null


#Site config
title: çˆ±è„‘è¡¥
description: çˆ±è„‘è¡¥
keywords: iOS Swift Objective-C ç§»åŠ¨ç«¯å¼€å‘
# url: http://blog.diguage.com
feed: /atom.xml
favicon: favicon.ico

#Nav config
nav:
  - text: é¦–é¡µ
    url: /
  - text: åˆ†ç±»ç›®å½•
    url: /categories/
  - text: æ–‡ç« å½’æ¡£
    url: /archives/
  - text: è”ç³»
    url: /contact.html
  - text: å‹æƒ…é“¾æ¥
    url: /links/

#Author config
author:
    name: çˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸ
    email: yring2007[a]163.com
    imageLink: avatar.jpeg
    simpleIntro: æˆ‘æ˜¯ã€Œçˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸã€ã€‚
    detailIntro:
      <p text-indent="3em"> Helloï¼Œæˆ‘æ˜¯çˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸï¼Œçƒ­çˆ±å’Œä»äº‹ç€è‹¹æœç§»åŠ¨ç«¯çš„APPå¼€å‘ã€‚åœ¨è¿™é‡Œï¼Œæˆ‘å°†æ‹¥æŠ±Swiftï¼Œè®°å½•å’ŒTaä¸€èµ·æˆé•¿çš„ç‚¹ç‚¹æ»´æ»´ï¼Œä¹ŸæœŸå¾…åœ¨è¿™é‡Œæœ‰æ›´å¤šçš„åˆ†äº«ï¼Œæ›´å¤šçš„äº¤æµï¼Œæ›´å¤šçš„è¿›æ­¥ã€‚</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  # - class: icon-weibo
    # url: http://weibo.com/pizn
  # - class: icon-renren
  #   url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/yanmai
  # - class: icon-twitter
  #   url: http://twitter.com/piznlin
  # - class: icon-google-plus
  #   url: http://google.com

#Links
customLinks:
  - item:
    - text: æˆ‘çš„ Github
      url: https://github.com/yanmai/
    - text: â€œåœ°ç“œå“¥â€åšå®¢ç½‘
      url: http://www.diguage.com/
    message: Friends
  - item:
    - text: Apple Developer
      url: https://developer.apple.com/develop/
    - text: Hacker News
      url: https://news.ycombinator.com/
    - text: StackOverflow
      url: http://stackoverflow.com/
    - text: Reddit
      url: https://www.reddit.com/
    - text: Ray Wenderlich
      url: https://www.raywenderlich.com/
    - text: Code4App å¼€æºä»£ç åº“
      url: http://code4app.com/
    - text: UI4App UI ç´ æ
      url: http://ui4app.com/
    - text: å¼€å‘è€…å¤´æ¡
      url: https://toutiao.io/
    - text: ç å†œå‘¨åˆŠ
      url: http://weekly.manong.io/issues/
    - text: iOS å­¦ä¹ èµ„æ–™æ•´ç†
      url: https://github.com/Aufree/trip-to-iOS
    - text: CocoaChina
      url: http://www.cocoachina.com/
    - text: å”å·§çš„æŠ€æœ¯åšå®¢
      url: http://blog.devtang.com/
    - text: TouchArcade
      url: http://toucharcade.com/
    - text: Dribbble
      url: https://dribbble.com/
    message: å¼€å‘èµ„æº

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#googleAnaly, your id link UA-12345678-X
baiduAnaly:
  config: true
  id: a89a524322e6a3e17b2bc7a342fe2e7b

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: false
  id: zhanxin
