# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     10

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     /:year/:month/:day/:title.html
paginate_path: /page/:num
timezone:      null


#Site config
title: çˆ±è„‘è¡¥
description: çˆ±è„‘è¡¥
keywords: iOS Swift Objective-C ç§»åŠ¨ç«¯å¼€å‘
# url: http://blog.diguage.com
feed: /atom.xml
favicon: favicon.ico

#Nav config
nav:
  - text: é¦–é¡µ
    url: /
  - text: åˆ†ç±»ç›®å½•
    url: /categories/
  - text: æ–‡ç« å½’æ¡£
    url: /archives/
  - text: è”ç³»
    url: /contact.html
  - text: å‹æƒ…é“¾æ¥
    url: /links/
  # - text: æŠ€æœ¯æ”¯æŒ
  #   url: /technologies/

#Author config
author:
    name: çˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸ
    email: yring2007[a]163.com
    imageLink: avatar.jpeg
    simpleIntro: æˆ‘æ˜¯ã€Œçˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸã€ã€‚
    detailIntro:
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Helloï¼Œæˆ‘æ˜¯çˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸï¼Œçƒ­çˆ±å’Œä»äº‹ç€è‹¹æœç§»åŠ¨ç«¯çš„APPå¼€å‘ã€‚Swiftä½œä¸ºè‹¹æœå…¬å¸åŠ›æ¨çš„iOSç¼–ç¨‹çš„æ–°å® å„¿ï¼Œä¸€äº›æ–°çš„é¡¹ç›®ç›®å‰å·²ç»ä½¿ç”¨äº†Swiftã€‚ä¸ºäº†ä¸è®©è‡ªå·±è¢«è¿™è‚¡æµªæ½®æ— æƒ…çš„æ·˜æ±°ï¼Œæ‰€ä»¥æ¬£ç„¶åœ°æ¥å—äº†ä»–ã€‚</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;åœ¨è¿™é‡Œï¼Œçˆ±è„‘è¡¥çš„è‹¹æœå®è´ğŸå°†æ‹¥æŠ±Swiftï¼Œè®°å½•å’Œä»–ä¸€èµ·æˆé•¿çš„ç‚¹ç‚¹æ»´æ»´ï¼Œä¹ŸæœŸå¾…åœ¨è¿™é‡Œæœ‰æ›´å¤šçš„åˆ†äº«ï¼Œæ›´å¤šçš„äº¤æµï¼Œæ›´å¤šçš„è¿›æ­¥ã€‚</p>
#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  # - class: icon-weibo
    # url: http://weibo.com/pizn
  # - class: icon-renren
  #   url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/yanmai
  # - class: icon-twitter
  #   url: http://twitter.com/piznlin
  # - class: icon-google-plus
  #   url: http://google.com

#Links
customLinks:
  - item:
    - text: â€œåœ°ç“œå“¥â€åšå®¢ç½‘
      url: http://www.diguage.com/
    - text: Scott Liu
      url: http://blog.csdn.net/liuhe688
    message: å‹æƒ…é“¾æ¥
  - item:
    - text: Apple Developer
      url: https://developer.apple.com/develop/
    - text: Hacker News
      url: https://news.ycombinator.com/
    - text: StackOverflow
      url: http://stackoverflow.com/
    - text: Awesome iOS
      url: https://github.com/vsouza/awesome-ios
    - text: Reddit
      url: https://www.reddit.com/
    - text: Ray Wenderlich
      url: https://www.raywenderlich.com/
    - text: TouchArcade
      url: http://toucharcade.com/
    - text: Dribbble
      url: https://dribbble.com/
    message: è‹±æ–‡èµ„æ–™
  - item:
    - text: å¼€å‘è€…å¤´æ¡
      url: https://toutiao.io/
    - text: ç å†œå‘¨åˆŠ
      url: http://weekly.manong.io/issues/
    - text: iOSå¤´æ¡
      url: https://toutiao.io/c/ios
    - text: Code4App å¼€æºä»£ç åº“
      url: http://code4app.com/
    - text: UI4App UI ç´ æ
      url: http://ui4app.com/
    - text: iOS å­¦ä¹ èµ„æ–™æ•´ç†
      url: https://github.com/Aufree/trip-to-iOS
    - text: CocoaChina
      url: http://www.cocoachina.com/
    - text: å”å·§çš„æŠ€æœ¯åšå®¢
      url: http://blog.devtang.com/
    - text: 36æ°ª
      url: http://36kr.com/
    - text: V2EX
      url: https://www.v2ex.com/
    - text: CSDN - å…¨çƒæœ€å¤§ä¸­æ–‡ITç¤¾åŒº
      url: http://www.csdn.net/
    - text: åšå®¢å›­
      url: http://www.cnblogs.com/
    - text: å¼€æºä¸­å›½
      url: http://www.oschina.net/
    - text: è±†ç“£
      url: https://www.douban.com/
    message: ä¸­æ–‡èµ„æ–™
  - item:
    - text: Coursera
      url: https://www.coursera.org/
    - text: ä¼˜è¾¾å­¦åŸ
      url: https://cn.udacity.com/
    - text: ç½‘æ˜“äº‘è¯¾å ‚
      url: http://study.163.com/
    - text: ç½‘æ˜“å…¬å¼€è¯¾
      url: https://open.163.com/
    - text: æå®¢å­¦é™¢
      url: http://www.jikexueyuan.com/
    - text: æ…•è¯¾ç½‘
      url: http://www.imooc.com/
    - text: edX
      url: https://www.edx.org/edxchina
    - text: Mooc å­¦é™¢
      url: http://mooc.guokr.com/
    message: åœ¨çº¿è¯¾ç¨‹

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#googleAnaly, your id link UA-12345678-X
baiduAnaly:
  config: true
  id: c4c519196d1010885e0fe43b3f2d0f06

#comment config
uyan:
  config: true
  id: 897628

changyan:
  config: false
  appid: cysQKdOgt
  conf: prod_e0ea3cce552a301b41ab033a41424e94
